#!/bin/sh

start() {
 	echo -n "Initializing Fixups: "

	mount /nfs

	echo "OK"
}	
stop() {
	echo -n "Uninitializing Fixups: "

	umount /nfs

	echo "OK" 
}
restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

